//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentRussia
    {
        public string Name { get; set; }
        public Nullable<double> Inn { get; set; }
        public Nullable<double> Kpp { get; set; }
        public string RS { get; set; }
        public string Bic { get; set; }
        public string Ks { get; set; }
        public string Kbk { get; set; }
        public string Okato { get; set; }
        public Nullable<int> KassFlag { get; set; }
        public Nullable<double> TaxPercent { get; set; }
        public Nullable<double> TaxMin { get; set; }
        public Nullable<double> TaxMax { get; set; }
        public int Id { get; set; }
    }
}
