//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT
    {
        public int ID_SERV { get; set; }
        public string N_SERV { get; set; }
        public int ID_SYST { get; set; }
        public string N_SYST { get; set; }
        public float TAX3 { get; set; }
        public float TAX4 { get; set; }
        public int KOD_PL { get; set; }
        public string INN { get; set; }
        public string RSRUB { get; set; }
        public string KORSC { get; set; }
        public string BIC { get; set; }
        public string BANKRUB { get; set; }
        public string TRANZIT { get; set; }
        public string FULL_NAME { get; set; }
        public string EMAIL { get; set; }
        public string DOP_NAZN { get; set; }
        public string KASS_SIMVOL { get; set; }
        public Nullable<int> REGION { get; set; }
        public string KEY_REGION { get; set; }
        public System.Guid Id { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<float> MaxCommission { get; set; }
        public string OKATO { get; set; }
        public string KBK { get; set; }
        public string KPP { get; set; }
        public string LS { get; set; }
        public Nullable<int> KOMUN { get; set; }
    }
}
