//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Altfater
    {
        public string FIO { get; set; }
        public string LS { get; set; }
        public string ULICA { get; set; }
        public string NOMDOMA { get; set; }
        public string NOMKWAR { get; set; }
        public Nullable<double> ADRESS { get; set; }
        public int ID { get; set; }
    }
}
