//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUDJET_SHABLON
    {
        public string INN { get; set; }
        public string RS { get; set; }
        public string KPP { get; set; }
        public string BIC { get; set; }
        public string BANK { get; set; }
        public string KBK { get; set; }
        public string OKATO { get; set; }
        public string PURPOSE { get; set; }
        public string TAXNUMBER { get; set; }
        public string AGENT { get; set; }
        public string UIN { get; set; }
        public double DOCUMENTID { get; set; }
        public double PERSONID { get; set; }
        public string FIO { get; set; }
        public string ADRESS { get; set; }
        public int id { get; set; }
    }
}
