//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IRCFIZIKIEntities : DbContext
    {
        public IRCFIZIKIEntities()
            : base("name=IRCFIZIKIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BUDJET_SHABLON> BUDJET_SHABLON { get; set; }
        public virtual DbSet<KLIENTS_FIZ> KLIENTS_FIZ { get; set; }
        public virtual DbSet<STORNO_FIZ> STORNO_FIZ { get; set; }
    }
}
