//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KassSymbol
    {
        public string Name { get; set; }
        public string Symbol { get; set; }
        public int Key_id { get; set; }
        public string FullName { get; set; }
    }
}
