//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KassOrder
    {
        public decimal Number { get; set; }
        public string Data { get; set; }
        public string Debet { get; set; }
        public string Kredet { get; set; }
        public string PayerFio { get; set; }
        public string Agent { get; set; }
        public string Rs { get; set; }
        public string Inn { get; set; }
        public string Branch { get; set; }
        public string BankTo { get; set; }
        public string BankToBic { get; set; }
        public string BranchBic { get; set; }
        public string Simvol { get; set; }
        public string Summa { get; set; }
        public string SummaString { get; set; }
        public string Purpose { get; set; }
        public bool IsTaxes { get; set; }
        public decimal Id { get; set; }
        public int KeyId { get; set; }
        public Nullable<int> Kass { get; set; }
    }
}
