//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KASSESDB_
    {
        public Nullable<double> ID_SYST { get; set; }
        public Nullable<double> NP { get; set; }
        public string PACHKA { get; set; }
        public string SC { get; set; }
        public string KOMIS_S_KL { get; set; }
        public Nullable<double> PART { get; set; }
        public string CITY { get; set; }
        public Nullable<double> CLOSE { get; set; }
        public Nullable<int> AVTOSALON { get; set; }
        public Nullable<int> IsOKVKU { get; set; }
        public string PACHKA_VNESH { get; set; }
        public string TRANZIT_VNESH { get; set; }
        public string NDS_KOMISS { get; set; }
        public string NDS_SCH { get; set; }
        public string VALUT_SCH { get; set; }
        public string VALUT_SCH_E { get; set; }
        public string ROSMED { get; set; }
        public int Id { get; set; }
        public Nullable<int> FilialId { get; set; }
        public string KOMISS_P { get; set; }
        public string KOMISS_SC { get; set; }
        public string PACHKA_VNUT { get; set; }
    }
}
