//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KLIENTS_FIZ
    {
        public double PersonID { get; set; }
        public string FIO { get; set; }
        public string ADRES { get; set; }
        public string GOROD { get; set; }
        public string ULICA { get; set; }
        public string DOM { get; set; }
        public string KVARTIRA { get; set; }
        public int Id { get; set; }
        public Nullable<double> DocumentId { get; set; }
    }
}
