//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KLIENTS
    {
        public int NUMBER { get; set; }
        public string FAMILIYA { get; set; }
        public string IMYA { get; set; }
        public string OTCHESTVO { get; set; }
        public string GOROD { get; set; }
        public string ULICA { get; set; }
        public string DOM { get; set; }
        public string KVARTIRA { get; set; }
        public Nullable<int> CODE { get; set; }
        public string TELEFON { get; set; }
        public string PASPORT_S { get; set; }
        public string PASPORT_N { get; set; }
        public string BIRTHDAY { get; set; }
        public Nullable<double> DiasoftId { get; set; }
        public string FULL_NAME { get; set; }
        public string FULL_ADRES { get; set; }
    }
}
