//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loging
    {
        public string Data { get; set; }
        public int N_KASS { get; set; }
        public string KASSIR { get; set; }
        public string ERROR { get; set; }
        public int Id { get; set; }
    }
}
