//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plat_por
    {
        public string Data { get; set; }
        public string Number { get; set; }
        public string Summ_propis { get; set; }
        public string Summ { get; set; }
        public string Schet_plat { get; set; }
        public string Bic_plat { get; set; }
        public string K_schet_plat { get; set; }
        public string Bank_plat { get; set; }
        public string Inn_otp { get; set; }
        public string Plat { get; set; }
        public string Bank_pol { get; set; }
        public string Pol { get; set; }
        public string Inn_pol { get; set; }
        public string Kpp_pol { get; set; }
        public string Bic_pol { get; set; }
        public string Schet_pol { get; set; }
        public string K_schet_pol { get; set; }
        public string Nazn_pol { get; set; }
        public decimal Id { get; set; }
        public string Uin { get; set; }
        public string Kbk { get; set; }
        public string Okato { get; set; }
        public string Nal_osn { get; set; }
        public string Nal_per { get; set; }
        public string Nal_nom { get; set; }
        public string Drow_stat { get; set; }
        public int Key_id { get; set; }
        public Nullable<int> Kass { get; set; }
        public string PayerInn { get; set; }
    }
}
