//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Porych
    {
        public string Data { get; set; }
        public string Fio { get; set; }
        public string SummaPlat { get; set; }
        public string SummaPlatString { get; set; }
        public string Adres { get; set; }
        public string Doc { get; set; }
        public string Agent { get; set; }
        public string AgentInn { get; set; }
        public string AgentSc { get; set; }
        public string AgentBank { get; set; }
        public string AgentCor { get; set; }
        public string AgentBic { get; set; }
        public string Purpose { get; set; }
        public string SummaTax { get; set; }
        public string SummaTaxString { get; set; }
        public string SummaAllString { get; set; }
        public string OperatorButi { get; set; }
        public string OperatorFio { get; set; }
        public int key_Id { get; set; }
        public Nullable<int> Kass { get; set; }
        public Nullable<decimal> Number { get; set; }
        public string StatSost { get; set; }
        public string Kbk { get; set; }
        public string Okato { get; set; }
        public string OsnPlat { get; set; }
        public string NalPer { get; set; }
        public string NumberDoc { get; set; }
        public string DataDoc { get; set; }
        public string TypePlat { get; set; }
        public string Index { get; set; }
        public Nullable<decimal> Id { get; set; }
    }
}
