//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IRCRUSSIAEntities : DbContext
    {
        public IRCRUSSIAEntities()
            : base("name=IRCRUSSIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KassOrder> KassOrder { get; set; }
        public virtual DbSet<KassOrderAccount> KassOrderAccount { get; set; }
        public virtual DbSet<Plat_por> Plat_por { get; set; }
        public virtual DbSet<Porych> Porych { get; set; }
    }
}
