//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GateWay.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORNO_FIZ
    {
        public int NUMBER { get; set; }
        public string DEBET { get; set; }
        public string KREDIT { get; set; }
        public string NAZN { get; set; }
        public string PACHKA { get; set; }
        public double SUMMA { get; set; }
        public int N_KASS { get; set; }
        public int N_AGENT { get; set; }
        public string LS { get; set; }
        public double N_KLI { get; set; }
        public string DATA { get; set; }
        public int STATUS { get; set; }
        public string PACKET_IDENT { get; set; }
        public string BRANCH { get; set; }
        public string KASSIR { get; set; }
    }
}
